const { FAILURE_CODES } = require("./index");

const FAILURE_METADATA = Object.freeze({
  [FAILURE_CODES.TALLY_STOPPED]: {
    retryable: true,
    severity: "CRITICAL",
    diagnosticHint: "TallyPrime service is not reachable. Verify Tally is open and the HTTP server is enabled under F1: Help > Settings > Connectivity.",
    userAction: "Start TallyPrime and ensure server mode is enabled."
  },
  [FAILURE_CODES.WRONG_PORT]: {
    retryable: true,
    severity: "HIGH",
    diagnosticHint: "Target port refused connection. Configured TALLY_PORT does not match TallyPrime's listening port.",
    userAction: "Check Tally connectivity port in TallyPrime settings and update TALLY_PORT in .env."
  },
  [FAILURE_CODES.CONNECTION_REFUSED]: {
    retryable: true,
    severity: "CRITICAL",
    diagnosticHint: "TCP connection refused on configured host and port.",
    userAction: "Verify TallyPrime is running and configured port is active."
  },
  [FAILURE_CODES.CONNECTION_TIMEOUT]: {
    retryable: true,
    severity: "HIGH",
    diagnosticHint: "Request to TallyPrime timed out. Tally may be busy or frozen by a modal dialog.",
    userAction: "Check if Tally has open dialog prompts (e.g. Educational Mode) and close them."
  },
  [FAILURE_CODES.TALLY_PAUSED]: {
    retryable: true,
    severity: "HIGH",
    diagnosticHint: "TallyPrime accepted the connection but never answered, so requests are paused instead of piling up behind timeouts. The connection is retried automatically.",
    userAction: "Close any dialog open in TallyPrime, then check Task Manager for a second tally.exe — if an older one is holding the connectivity port, the TallyPrime window you can see never bound it. No restart is needed once the port is free; the app reconnects on its own."
  },
  [FAILURE_CODES.TALLY_BUSY]: {
    retryable: true,
    severity: "LOW",
    diagnosticHint: "TallyPrime was still finishing an earlier query, so this request gave up its place in the queue instead of waiting.",
    userAction: "Retry in a moment. Large extractions hold TallyPrime for a while because it processes one request at a time."
  },
  [FAILURE_CODES.NO_COMPANY]: {
    retryable: true,
    severity: "MEDIUM",
    diagnosticHint: "Tally is responding but no active company is loaded in the workspace.",
    userAction: "Open the target company in TallyPrime."
  },
  [FAILURE_CODES.MALFORMED_XML]: {
    retryable: false,
    severity: "HIGH",
    diagnosticHint: "Response received from Tally could not be parsed as valid XML.",
    userAction: "Inspect raw response payload for syntax anomalies or encoding issues."
  },
  [FAILURE_CODES.TALLY_INVALID_COLLECTION]: {
    retryable: false,
    severity: "HIGH",
    diagnosticHint: "Tally could not resolve the requested collection definition.",
    userAction: "Verify that HEADER.ID exactly matches the COLLECTION NAME defined inside TDLMessage, and that the collection declares a <TYPE>."
  },
  [FAILURE_CODES.LINE_ERROR]: {
    retryable: false,
    severity: "HIGH",
    diagnosticHint: "Tally processed the request but returned a <LINEERROR> indicating a TDL or query failure.",
    userAction: "Check TDL request compatibility with the running TallyPrime release."
  },
  [FAILURE_CODES.INVALID_ENVELOPE]: {
    retryable: false,
    severity: "HIGH",
    diagnosticHint: "XML response is missing the required root <ENVELOPE> or <HEADER> structure.",
    userAction: "Verify Tally server response format settings."
  },
  [FAILURE_CODES.EMPTY_RESPONSE]: {
    retryable: true,
    severity: "MEDIUM",
    diagnosticHint: "Tally returned an empty body (0 bytes).",
    userAction: "Check Tally status and retry."
  },
  [FAILURE_CODES.UNEXPECTED_RESPONSE]: {
    retryable: true,
    severity: "MEDIUM",
    diagnosticHint: "Tally returned an unexpected HTTP status code or payload format.",
    userAction: "Review bridge logs and Tally connection settings."
  },
  [FAILURE_CODES.READ_ONLY_VIOLATION]: {
    retryable: false,
    severity: "CRITICAL",
    diagnosticHint: "Outbound request was rejected by ReadOnlyPolicy because it contains write/import/mutation commands.",
    userAction: "Ensure only read-only export queries are generated by the bridge."
  },
  [FAILURE_CODES.UNKNOWN_ERROR]: {
    retryable: true,
    severity: "HIGH",
    diagnosticHint: "An unclassified error occurred during communication with Tally.",
    userAction: "Check logs for detailed stack trace and diagnose connectivity."
  }
});

module.exports = {
  FAILURE_CODES,
  FAILURE_METADATA
};
