/**
 * System Constants for CFO Yantra Tally Bridge
 */

const FAILURE_CODES = Object.freeze({
  TALLY_STOPPED: "TALLY_STOPPED",
  WRONG_PORT: "WRONG_PORT",
  CONNECTION_REFUSED: "CONNECTION_REFUSED",
  CONNECTION_TIMEOUT: "CONNECTION_TIMEOUT",
  TALLY_PAUSED: "TALLY_PAUSED",
  TALLY_BUSY: "TALLY_BUSY",
  NO_COMPANY: "NO_COMPANY",
  MALFORMED_XML: "MALFORMED_XML",
  LINE_ERROR: "LINE_ERROR",
  TALLY_INVALID_COLLECTION: "TALLY_INVALID_COLLECTION",
  INVALID_ENVELOPE: "INVALID_ENVELOPE",
  EMPTY_RESPONSE: "EMPTY_RESPONSE",
  UNEXPECTED_RESPONSE: "UNEXPECTED_RESPONSE",
  READ_ONLY_VIOLATION: "READ_ONLY_VIOLATION",
  UNKNOWN_ERROR: "UNKNOWN_ERROR"
});

const TALLY_REQUEST_TYPES = Object.freeze({
  EXPORT: "Export",
  COLLECTION: "Collection",
  REPORT: "Report"
});

const SECURITY = Object.freeze({
  DEFAULT_CIPHER: "aes-256-gcm",
  CHECKSUM_ALGORITHM: "sha256"
});

module.exports = {
  FAILURE_CODES,
  TALLY_REQUEST_TYPES,
  SECURITY
};
